config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :cats do
    resources :bookings, only: [:show, :new, :create, :destroy]
  end

  get 'dashboard' => 'pages#dashboard'
  get 'home' => 'pages#home'

  get '/' => 'pages#home'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :renter, :class_name => :User, :foreign_key => "user_id"
  belongs_to :cat
  validates :cat_id, presence: true
  # validates :user_id, presence: true
  # validates :renting_price, presence: true
  # validates :start_time, presence: true
    # validates :end_time, presence: true

    def duration
     end_date = Date.new(end_time.year, end_time.month, end_time.day)
     start_date = Date.new(start_time.year, start_time.month, start_time.day)
     (end_date - start_date).to_i
    end
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_city, :against => :city
  belongs_to :owner, :class_name => :User,:foreign_key => "user_id"
   validates :name, presence: true
   validates :description, presence: true
  # validates_inclusion_of :gender, :in => [1,2]
   validates :price, presence: true
   validates :zip_code, presence: true
   validates :city, presence: true
   validates :address, presence: true


  has_many :bookings
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>", small: "200x200>"}

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  geocoded_by :full_address
  after_validation :geocode, if: :address_changed?

  paginates_per 6

  def full_address
   [address, zip_code, city].compact.join(', ')
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :cats
  has_many :bookings


def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
 before_action :authenticate_user!
 skip_before_action :authenticate_user!, only: [ :show, :create]

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @cat = Cat.find(params[:cat_id])
    @booking = @cat.bookings.new(booking_params)
    @booking_total_price = @booking.duration * @cat.price
    @booking.renting_price = @booking_total_price
    @booking.renter = current_user
    if @booking.save
      redirect_to cat_booking_path(@cat, @booking)
    else
       render :new
     end
  end


  def booking_length

  end

   def total_price

    total = 0


    total
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :cat_id, :renting_price, :start_time, :end_time)
  end


end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_cats, only: [:show, :edit, :update, :destroy]

  def index

    @cats = Cat.all
    @markers = Gmaps4rails.build_markers(@cats) do |cat, marker|
      marker.lat cat.latitude
      marker.lng cat.longitude
    end
    if params[:city].present?
      @cats = Cat.search_by_city(params[:city]).order("created_at DESC").page(params[:page])
    else
      @cats = Cat.all.order('created_at DESC').page(params[:page])
    end
  end

  def show
    @alert_message = "You are viewing #{@cat.name}"
    @cat_coordinates = [{ lat: @cat.latitude, lng: @cat.longitude }]
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(params_cats)
    @cat.user_id = current_user.id

    if @cat.save
      redirect_to cat_path(@cat)
    else
       render :new
     end
  end

  def edit
    @cat.save
  end

  def update
    if @cat.update(params_cats)
      redirect_to cat_path(@cat)
    else
      render :edit
    end
  end

  def destroy
    if @cat.delete
      redirect_to cats_path
    else
      render :destroy
    end
  end

  private

  def set_cats
    @cat = Cat.find(params[:id])
  end

  def params_cats
    params.require(:cat).permit(:name, :description, :price, :gender, :race, :age, :zip_code, :city, :address, :picture)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @cats = Cat.all
  end

  def dashboard
    @cats = current_user.cats
    @bookings = current_user.bookings

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="thumbnail" style="margin-top:20px; background-color:#66CC99;">

        <div class="text-center">
          <h4><strong> Bravo vous venez de réserver votre chat !! </strong> </h4>
        </div>

      </div>
    </div>
  </div>
</div>



  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-center">

        <div class="img-rounded">
          <%= image_tag @booking.cat.picture(:medium) %>
           <h4 class="text-center" style="margin-top:20px;"> <strong> Récapitulatif de votre réserveration </strong> </h4>
          <h4 style="margin-top:20px;"><strong> <%= @booking.cat.name %></strong> a bien été réservé</h4>
          <h4> Vous l'avez réservé de <strong><%= @booking.start_time %> à <%= @booking.end_time %> </strong> </h4>
          <h4> Le prix total de la réservation est de:<strong> <%= @booking.renting_price %> euros</strong> </h4>

          <p>N'hésitez pas à nous contacter sur notre addresse contact@rentmycat.miaou</p>

     </div>
    </div>
  </div>
</div>

 <ul class="list-inline text-center">
          <li>  <%= link_to "Mon profil", dashboard_path, class: "btn btn-primary active btn-lg" %> </li>
          <li>  <%= link_to "Retour", cats_path, class: "btn btn-warning active btn-lg" %> </li>
 </ul>

app/views/cats/edit.html.erb
<div class="container form-new-cat">
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= simple_form_for @cat do |f| %>
  <%= f.input :name, label: 'Nom:', placeholder: 'Boris' %>
  <%= f.input :description %>
  <%= f.input :price, label: 'Prix par jour' %>
  <%= f.input :address, label: "Numéro et rue" %>
  <%= f.input :zip_code , label: "Code postal" %>
  <%= f.input :city, label: "Ville" %>

  <p><strong>Disponible dans l'immediat :</strong></p>
  <%= f.collection_check_boxes :availability, [[true, 'Oui'] ,[false, 'Non']], :first, :last %>

  <div class="text-center"><%= f.button :submit, "validez", class: "btn btn-success", style:"font-size:20px;" %></div>

<% end %>
  </div>
 </div>
</div>


<% content_for :after_js do %>

 <!-- Include Google Maps JS API -->
 <script type="text/javascript"
   src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key= AIzaSyAyi0K8taljUqo81J5MakHfzIzHFgrMg2U">
 </script>

 <!-- Custom JS code to bind to Autocomplete API -->
 <!-- find it here: https://github.com/lewagon/google-place-autocomplete/blob/gh-pages/autocomplete.js -->
 <!-- We'll detail this file in the article -->
 <!-- <script type="text/javascript" src="autocomplete.js"></script> -->
 <%= javascript_tag do %>
     google.maps.event.addDomListener(window, 'load', function() {
     initializeAutocomplete('user_input_autocomplete_city');
     });
 <% end %>

<% end %>

app/views/cats/index.html.erb
<div class="container" style="margin-bottom:200px" >


<div class="form-inline city" style="margin-top:50px">
  <div class="form-group">
    <%= form_tag('/cats', method: "get")  do %>
      <div class="form-group">
      <%= text_field_tag :city, nil, class: "form-control", placeholder: "Rechercher par ville", autosave: true, autofocus: true, style: "height:50px;width: 380px", id: "user_input_autocomplete_city" %>
        </div>
          <%= button_tag(type: "submit", class: "btn btn-success") do %>
            <h5>Rechercher</h5>
          <% end %>
    <% end %>
  </div>
</div>


   <div class="row">
    <div class="row col-xs-6 col-sm-6 col-md-6" style="margin-top: 27px">
      <% @cats.each do |cat| %>
        <div class="thumbnail card card-hover card-gradient col-xs-3 col-sm-3 col-md-3" style="background-image: url('<%=image_path cat.picture.url(:medium)%>')">
          <h2 class="hover"><%= cat.name %></h2>
          <strong><h4><%= cat.price %>€/jour</h4></strong>
          <p><%= cat.city %></p>

          <div class="list-inline">
            <div>
            <li class="position">
              <%if cat.availability == false %>
                <span style="color: red">Non disponible</span>
              <% else %>
                <span style="color: green">Disponible</span>
              <% end %>
            </li>
            </div>
            <li class="positions"><%= link_to "RESERVER", cat_path(cat), class: "btn btn-success" %></li>
          </div>
        </div>
      <% end %>

      <%= paginate @cats %>
    </div>


    <div class="container col-xs-6 col-sm-6 col-md-6">
    <div id="map" style="width: 100%; height: 759px;"></div>

    <% content_for(:after_js) do %>
      <%= javascript_tag do %>
        $(document).on('ready', function() {
          handler = Gmaps.build('Google');
          handler.buildMap({ internal: { id: 'map' } }, function(){
            markers = handler.addMarkers(<%= raw @markers.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
          });
        })
      <% end %>
    <% end %>
    </div>
 </div>
</div>

<% content_for :after_js do %>

 <!-- Include Google Maps JS API -->
 <script type="text/javascript"
   src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key= AIzaSyAyi0K8taljUqo81J5MakHfzIzHFgrMg2U">
 </script>

 <!-- Custom JS code to bind to Autocomplete API -->
 <!-- find it here: https://github.com/lewagon/google-place-autocomplete/blob/gh-pages/autocomplete.js -->
 <!-- We'll detail this file in the article -->
 <!-- <script type="text/javascript" src="autocomplete.js"></script> -->
 <%= javascript_tag do %>
     google.maps.event.addDomListener(window, 'load', function() {
     initializeAutocomplete('user_input_autocomplete_city');
     });
 <% end %>

<% end %>

app/views/cats/new.html.erb
<div class="container form-new-cat" style="margin-top: 50px;
margin-left: 30px;">
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= simple_form_for @cat do |f| %>

  <%= f.input :name, label: 'Nom:',input_html: {:maxlength => 10}, placeholder: 'Boris' %>
  <%= f.input :picture, label: 'Photo' %>
  <%= f.input :description, placeholder: 'Décrivez le au maximum! (son age, son caractère, etc...)' ,input_html: {:maxlength => 20} %>
  <%= f.input :price, label: 'Prix par jour', placeholder: 'Mettre au moins 0 si pas de prix' %>
  <%= f.input :address, label: "Numéro et rue" %>
  <%= f.input :zip_code , label: "Code postal" %>
  <%= f.input :city, label: "Ville", input_html: {id: "user_input_autocomplete_city"} %>

  <p><strong>Disponible dans l'immediat :</strong></p>
  <%= f.collection_check_boxes :availability, [[true, 'Oui'] ,[false, 'Non']], :first, :last %>
  <div class="text-center" style="margin-bottom:15px"><%= f.button :submit, "valider", class: "btn btn-success", style: "font-size:20px;" %></div>

<% end %>
  </div>
 </div>
</div>

<% content_for :after_js do %>

 <!-- Include Google Maps JS API -->
 <script type="text/javascript"
   src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key= AIzaSyAyi0K8taljUqo81J5MakHfzIzHFgrMg2U">
 </script>

 <!-- Custom JS code to bind to Autocomplete API -->
 <!-- find it here: https://github.com/lewagon/google-place-autocomplete/blob/gh-pages/autocomplete.js -->
 <!-- We'll detail this file in the article -->
 <!-- <script type="text/javascript" src="autocomplete.js"></script> -->
 <%= javascript_tag do %>
     google.maps.event.addDomListener(window, 'load', function() {
     initializeAutocomplete('user_input_autocomplete_city');
     });
 <% end %>

<% end %>

app/views/cats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">

        <div class="thumb-container">
          <div class="thumbnail">
             <table>
               <thead>
                   <tr>
                       <th> <%= image_tag @cat.picture.url(:small) %> </th>
                       <th style="padding:10px;">  <h4><strong><%= @cat.name %></strong></h4>
                      <p> <strong> Description: </strong> <%= @cat.description %></p>
                      <p> <strong> Prix par jour: </strong> <%= number_to_currency(@cat.price, :unit => "€") %></p>
                      <p><%= @cat.race %></p> </th>
                    </tr>
                </thead>
            </table>
        </div>
      </div>






        <div class="thumbnail">
        <%= simple_form_for [@cat, @cat.bookings.new] do |f| %>
        <%= f.input :start_time, label: 'Début de la réservation' %>
        <%= f.input :end_time, label: 'Fin de la réservation' %>
        <ul class="list-inline">
          <li>  <%= f.submit "Réserver", class: "btn btn-success active" %> </li>
          <li>  <%= link_to "retour", cats_path, class: "btn btn-warning active" %> </li>
        </ul>

       </div>
        <% end %>
    </div>

        <div class="col-md-6">
          <h1>Adresse: </h1>
          <%= @cat.address %>
          <%= @cat.zip_code %>
          <%= @cat.city %>






    <div id="map" style="width: 100%; height: 500px;"></div>

      <% content_for(:after_js) do %>
        <%= javascript_tag do %>
          $(document).on('ready', function() {
            handler = Gmaps.build('Google');

            var styleArray = [{"featureType":"water","elementType":"geometry","stylers":[{"color":"#e9e9e9"},{"lightness":17}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#ffffff"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#ffffff"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#ffffff"},{"lightness":16}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#f5f5f5"},{"lightness":21}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#dedede"},{"lightness":21}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#ffffff"},{"lightness":16}]},{"elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#333333"},{"lightness":40}]},{"elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#f2f2f2"},{"lightness":19}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#fefefe"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#fefefe"},{"lightness":17},{"weight":1.2}]}];

            handler.buildMap({
                provider: {
                    maxZoom: 14,
                    styles: styleArray
                },
                internal: { id: 'map' }
              },
              function(){
              markers = handler.addMarkers(<%= raw @cat_coordinates.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();

            <!-- var coord = <%= raw @cat_coordinates %>; -->
            <!-- alert('Cat coordinates are ' + coord.lat + ', ' + coord.lng); -->
          });
        });
        <% end %>
      <% end %>


    </div>
  </div>
</div>

<% content_for :after_js do %>

 <!-- Include Google Maps JS API -->
 <script type="text/javascript"
   src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key= AIzaSyAyi0K8taljUqo81J5MakHfzIzHFgrMg2U">
 </script>

 <!-- Custom JS code to bind to Autocomplete API -->
 <!-- find it here: https://github.com/lewagon/google-place-autocomplete/blob/gh-pages/autocomplete.js -->
 <!-- We'll detail this file in the article -->
 <!-- <script type="text/javascript" src="autocomplete.js"></script> -->
 <%= javascript_tag do %>
     google.maps.event.addDomListener(window, 'load', function() {
     initializeAutocomplete('user_input_autocomplete_city');
     });
 <% end %>

<% end %>

app/views/layouts/_footer.html.erb
<div class:"container share-links">
  <div class:"row">
    <div class="share-links-item">

      <a href="#" class="share-links-item bg-facebook">
        <i class="fa fa-facebook"></i>
      </a>
      <a href="#" class="share-links-item bg-twitter">
        <i class="fa fa-twitter"></i>
      </a>
      <a href="#" class="share-links-item bg-email">
        <i class="fa fa-envelope-o"></i>
      </a>
      <a href="#" class="share-links-item bg-text">
        <i class="fa fa-mobile"></i>
      </a>

    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar-wagon navbar-wagon-fixed">
  <div class="container navbar-wagon-container">

    <a href="/">
      <%= image_tag "chatlogo.png" %>
    </a>
    <h2 class="transparent"><i>RentMyCat</i></h2>

    <div class="navbar-wagon-pusher"></div>
    <% if user_signed_in? %>
      <%= link_to "LOUER SON CHAT", new_cat_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "MON PROFIL", dashboard_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "LOG OUT",  destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn", method: :delete %>
      <%= image_tag current_user.picture, style:"height:80%", class: "navbar-wagon-item" %>
      <p style="color:#FFFFFF;"> <strong> <%= current_user.first_name %>
          <%= current_user.last_name %> </strong> </p>

    <% else %>
      <%= link_to "LOUER SON CHAT", new_cat_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "LOG IN" ,  new_user_session_path,      class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "SIGN UP",  new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentMyPet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render "layouts/navbar" %>
  <%= yield %>
  <%= render "layouts/footer" %>

<%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
<%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

<%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false&key=*****************" %>


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield(:after_js) %>
</body>
</html>

app/views/pages/dashboard.html.erb
<div id="dashboard-page-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12" >
        <div class="thumbnail" style="background-color:#FFFAEF; padding:10px;">
    Bonjour <%= current_user.first_name %>, bienvenue sur votre profil! Vous pouvez y consulter l'historique de vos réservations ainsi que les profils de vos chats.
        </div>
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
       <div class="col-xs-12 col-sm-6" >
          <div class="thumbnail" style="background-color:#FFFAEF">
             <h4 class="text-center"> Mes réservations </h4>
                <% @bookings.each do |booking| %>
           <div class="table-responsive" style="background-color:#FFFAEF">
              <table class="table">
                <thead>
                  <tr>

                    <th> Chat </th>
                    <th> Début </th>
                    <th> Fin </th>
                    <th> Prix </th>
                   </tr>
                </thead>
                     <tbody>
                        <tr>

                          <td> <%= booking.cat.name %> </td>
                          <td> <%= booking.start_time %> </td>
                          <td> <%= booking.end_time %> </td>
                          <td> <%= booking.renting_price %> </td>

                      <% end %>
                        </tr>
                     </tbody>
             </table>
        </div>
      </div>
      <%= link_to "Retour", cats_path, class: "btn btn-warning" %>
    </div>


      <div class="col-xs-12 col-sm-6" >
        <div class="thumbnail" style="background-color:#FFFAEF">
          <h4 class="text-center">Mes chats</h4>
        </div>
            <% @cats.each do |cat| %>
                <div class="thumbnail card card-gradient col-xs-3 col-sm-3 col-md-3" style="background-image: url('<%=image_path cat.picture.url(:medium)%>'); margin-left:10px; margin-right:15px;">
                  <p style="font-size:20px;"><%= cat.name %></p>
                    <ul class="list-inline btn" style=" margin-top: 160px; padding-left: 0px;">
                      <li><%= link_to "Supprimer", cat_path(cat), method: :delete, class:"btn btn-warning" %></li>
                      <li><%= link_to "Modifier les infos", edit_cat_path(cat), class:"btn btn-primary" %></li>
                    </ul>

                </div>
  <% end %>
          </div>
      </div>


</div>


<% content_for :after_js do %>

 <!-- Include Google Maps JS API -->
 <script type="text/javascript"
   src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key= AIzaSyAyi0K8taljUqo81J5MakHfzIzHFgrMg2U">
 </script>

 <!-- Custom JS code to bind to Autocomplete API -->
 <!-- find it here: https://github.com/lewagon/google-place-autocomplete/blob/gh-pages/autocomplete.js -->
 <!-- We'll detail this file in the article -->
 <!-- <script type="text/javascript" src="autocomplete.js"></script> -->
 <%= javascript_tag do %>
     google.maps.event.addDomListener(window, 'load', function() {
     initializeAutocomplete('user_input_autocomplete_city');
     });
 <% end %>

<% end %>

app/views/pages/home.html.erb
<div class= "home-container" >
   <div id="banner-image">
      <div id="banner-title">
         <h2><i class="fa fa-paw"> Louez un chat à côté de chez vous</i></h2>

            <div class="form-inline city">
              <div class="form-group yooo">
             <%= form_tag('/cats', method: "get")  do %>
                <div class="form-group">
                  <%= text_field_tag :city, nil, class: "form-control", placeholder: "Rechercher par ville", autosave: true, autofocus: true, style: "height:55px;width: 300px", id: "user_input_autocomplete_city" %>
                </div>
                  <%= button_tag(type: "submit", class: "btn btn-success") do %>
                    <h5>Rechercher</h5>
                  <% end %>
              <% end %>
            </div>
          </div>

      </div>
   </div>

  <div id="last-cats-added-container" class="text-center">
      <h2><i class="fa fa-heart"> Nos derniers coups de coeur</i></h2>
      <div class="container">
        <div class="row">
          <% @cats.last(4).each do |cat| %>
            <div class="col-xs-12 col-sm-3 card-home banner-gradient" style= "background-image: url('<%= image_path cat.picture.url(:medium)%>'); background-size:cover;" >
              <div style="margin-top:150px">
              <h2><%= link_to cat.name, cat_path(cat), class: "link-name" %></h2>
              <strong><%= number_to_currency(cat.price, :unit => "€") + "/" + "jour" %></strong>
              <p><%= cat.city %></p>
             </div>

            </div>
           <% end %>
        </div>
      </div>
  </div>
</div>


<% content_for :after_js do %>

  <!-- Include Google Maps JS API -->
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key= AIzaSyAyi0K8taljUqo81J5MakHfzIzHFgrMg2U">
  </script>

  <!-- Custom JS code to bind to Autocomplete API -->
  <!-- find it here: https://github.com/lewagon/google-place-autocomplete/blob/gh-pages/autocomplete.js -->
  <!-- We'll detail this file in the article -->
  <!-- <script type="text/javascript" src="autocomplete.js"></script> -->
  <%= javascript_tag do %>
      google.maps.event.addDomListener(window, 'load', function() {
      initializeAutocomplete('user_input_autocomplete_city');
      });
  <% end %>

<% end %>

app/views/shared/_footer.html.erb
<footer class: "share-links ">
<div class="share-links">
  <a href="#" class="share-links-item bg-facebook">
    <i class="fa fa-facebook"></i>
  </a>
  <a href="#" class="share-links-item bg-twitter">
    <i class="fa fa-twitter"></i>
  </a>
  <a href="#" class="share-links-item bg-email">
    <i class="fa fa-envelope-o"></i>
  </a>
  <a href="#" class="share-links-item bg-text">
    <i class="fa fa-mobile"></i>
  </a>
</div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon navbar-wagon-fixed">
  <div class="container navbar-wagon-container">

    <a href="/">
      <%= image_tag "chatlogo.png" %>
    </a>

    <div class="navbar-wagon-pusher"></div>
    <% if user_signed_in? %>
      <%= link_to "LOG OUT",  destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn", method: :delete %>
    <% else %>
      <%= link_to "LOG IN" ,  new_user_session_path,      class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "SIGN UP",  new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>
</nav>